### ISSUE TITLE
ReleaseProcessor types

### ISSUE THREAD

**Issue by facing-n** [nina-protocol/nina-indexer#760]
remaining types and references in indexerV1:
- [x]  `ReleasePurchaseViaHub` - [`addCollectorToRelease()`](https://github.com/nina-protocol/nina-indexer/blob/79a5a0ba2fcbbc8a2667a1d8c438ea2a458af7a3/indexer/processor.js#L258-L272
)
- [x]  `ReleasePurchase` - [`addCollectorToRelease()`](https://github.com/nina-protocol/nina-indexer/blob/79a5a0ba2fcbbc8a2667a1d8c438ea2a458af7a3/indexer/processor.js#L258-L272
)
- [x]  `ReleaseClaim`- [`addCollectorToRelease()`](https://github.com/nina-protocol/nina-indexer/blob/79a5a0ba2fcbbc8a2667a1d8c438ea2a458af7a3/indexer/processor.js#L258-L272
)
- [ ]  `ReleaseCloseEdition` - (im not sure we do anything with this on the indexer currently)
- [x]  `ReleaseUpdateMetadata` - [indexerV1 ref](https://github.com/nina-protocol/nina-indexer/blob/79a5a0ba2fcbbc8a2667a1d8c438ea2a458af7a3/indexer/processor.js#L665-L688)
- [x]  `ReleaseRevenueShareCollectViaHub` - [ `Release.processRevenueShares`](https://github.com/nina-protocol/nina-indexer/blob/79a5a0ba2fcbbc8a2667a1d8c438ea2a458af7a3/db/src/models/Release.js#L123-L140)
- [x]  `ReleaseRevenueShareCollect` - [ `Release.processRevenueShares`](https://github.com/nina-protocol/nina-indexer/blob/79a5a0ba2fcbbc8a2667a1d8c438ea2a458af7a3/db/src/models/Release.js#L123-L140)
- [x]  `ReleaseRevenueShareTransfer` - [ `Release.processRevenueShares`](https://github.com/nina-protocol/nina-indexer/blob/79a5a0ba2fcbbc8a2667a1d8c438ea2a458af7a3/db/src/models/Release.js#L123-L140)

additional notes for `ReleaseInit` and `ReleaseInitViaHub`:
- [x] the tags record inserting that happens [here](https://github.com/nina-protocol/nina-indexer/blob/79a5a0ba2fcbbc8a2667a1d8c438ea2a458af7a3/indexer/processor.js#L681-L684) should also be happening on `ReleaseInit` and `ReleaseInitViaHub`
- [x] `Release.processRevenueShares` - should also be called at the end of `ReleaseInit` and `ReleaseInitViaHub` where `releaseData` is the the Release account from the chain and `releaseRecord` is the postgres record for the newly created release

**Comment by bbnickell** [comment]
Last time we processed type='ReleaseCloseEdition':

```
Z='America/Chicago' date -r 1704745465           
Mon Jan  8 14:24:25 CST 2024
```
